---
#------------------------------------------------------------------------------
# - Run manage.py unit tests via Docker
# - Build from Dockerfile
# - Deploy to Kubernetes
#------------------------------------------------------------------------------
name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "**.py"
      - "smarter/**"
  pull_request_target:
    types: [closed]
    branches: [main]
    paths:
      - "**.py"
      - "smarter/**"

env:
  AWS_REGION: us-east-2
  ROOT_DOMAIN: "smarter.sh"

jobs:
  check_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - id: check
        run: |
          echo "::set-output name=merged::false"
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "::set-output name=merged::true"
          fi

      - name: Check branch name
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/alpha" && "${{ github.ref }}" != "refs/heads/beta" && "${{ github.ref }}" != "refs/heads/next" && "${{ github.ref }}" != "refs/heads/main" ]]; then
            echo "This workflow can only run on alpha, beta, next, or main branches"
            exit 1
          fi

  test:
    needs: check_merged
    if: ${{ needs.check_merged.outputs.merged == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4

      - name: Build
        uses: ./.github/actions/build
